#!/usr/bin/env bash
# .claude/hooks/graduated-@@TAG@@.sh — PreToolUse hook, rung 3 of 4.
#
# GENERATED by scripts/graduate.sh from @@CONVERSATIONS@@ distinct conversations.
# `graduate.sh present` redraws it from the rule table; hand edits are lost.
#
# THE CORRECTION IT ENFORCES
#   @@SENTENCE@@
#
# WHAT IT REFUSES
#   @@WHAT@@
#   on any judged line of the text the proposed action would introduce.
#
@@ASSERTS@@
#
# WHAT IT DOES NOT ASSERT, ON PURPOSE
#   Anything about the repository. This hook has never opened a file in it and
#   never will. A violation already sitting on disk — written before the hook
#   was installed, edited by a human outside the agent, or arriving in a merge —
#   is invisible here and is the ci-gate rung's job. A green hook is a statement
#   about one action, never about the tree.
#
#   Shell semantics. It matches TEXT: it does not normalise quoting, expand a
#   variable, or unwrap `sh -c`, so a spelling a shell would resolve can read
#   differently to it. templates/publish-gate.sh normalises before it matches
#   and is the pattern to copy when that gap starts to matter here.
#
# REGISTER IT ON THE MATCHERS IT UNDERSTANDS, AND ON NO OTHER. Fired on a tool
# whose payload it cannot read, it blocks rather than guesses, which is correct
# and also useless.
#
#   "hooks": { "PreToolUse": [ { "matcher": "@@MATCHER_RE@@",
#     "hooks": [ { "type": "command",
#       "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/graduated-@@TAG@@.sh" } ] } ] }
#
# EXIT CODES ARE THE CONTRACT.
#   0  allowed
#   2  BLOCKED. The tool call does not run; stderr goes back to the agent.
#   Anything else is NOT a block — Claude Code runs the tool anyway — so a hook
#   that crashes with 1 or 127 is a hook that allowed. Every failure path here
#   exits 2, this script's own bugs included, and the EXIT trap rewrites any
#   status that is not 0 into 2. A rung that cannot determine the answer must
#   never answer 0.
set -euo pipefail

_rc=2
trap '[ "$_rc" = 0 ] && exit 0; exit 2' EXIT

command -v python3 >/dev/null || {
  printf 'graduated-@@TAG@@: python3 is not on PATH, so this hook cannot read the payload it is meant to judge. Blocking, because an unread payload is not a clean one.\n' >&2
  exit 2
}

payload="$(cat)" || {
  printf 'graduated-@@TAG@@: could not read the hook payload from stdin. Blocking.\n' >&2
  exit 2
}

prc=0
printf '%s' "$payload" | python3 -c '
import json, re, sys

TAG      = "@@TAG@@"
WHAT     = "@@WHAT@@"
MATCHERS = @@MATCHERS@@
PATTERN  = r"@@PATTERN@@"
SKIP_SHELL_COMMENTS = @@SKIP_COMMENTS@@

# Every branch below is a shape this hook does not understand. It refuses each
# one. Guessing at a payload is how a gate approves something it never read.
def refuse(msg):
    sys.stderr.write("BLOCKED by graduated-%s.\n\n%s\n" % (TAG, msg))
    sys.exit(2)

raw = sys.stdin.read()
if not raw.strip():
    refuse("The payload was empty. A hook that cannot see what it is judging has not judged it.")
try:
    payload = json.loads(raw)
except ValueError as exc:
    refuse("The payload is not JSON (%s). Refusing rather than guessing at it." % exc)
if not isinstance(payload, dict):
    refuse("The payload is not a JSON object.")

tool = payload.get("tool_name")
if not isinstance(tool, str) or not tool:
    refuse("The payload names no tool_name, so this hook cannot tell which field carries the text it judges.")
if tool not in MATCHERS:
    refuse("Fired on tool %s. Register this hook on %s and nothing else: reading a payload shape it does not know would approve by accident." % (tool, "|".join(MATCHERS)))

tool_input = payload.get("tool_input")
if not isinstance(tool_input, dict):
    refuse("The payload carries no tool_input object, so there is nothing to read.")

FIELDS = {"Bash": ["command"], "Write": ["content"], "Edit": ["new_string"],
          "NotebookEdit": ["new_source"]}

texts = []
if tool == "MultiEdit":
    edits = tool_input.get("edits")
    if not isinstance(edits, list) or not edits:
        refuse("A MultiEdit payload carried no edits list, so the text it would write is unknown.")
    for edit in edits:
        if not isinstance(edit, dict) or not isinstance(edit.get("new_string"), str):
            refuse("A MultiEdit edit carried no new_string, so the text it would write is unknown.")
        texts.append(edit["new_string"])
else:
    for field in FIELDS[tool]:
        value = tool_input.get(field)
        if not isinstance(value, str):
            refuse("tool_input.%s is absent or not a string, so the text this %s would introduce is unknown." % (field, tool))
        texts.append(value)

rx = re.compile(PATTERN)
for text in texts:
    for n, line in enumerate(text.splitlines() or [text], 1):
        if SKIP_SHELL_COMMENTS and line.lstrip().startswith("#"):
            continue
        if rx.search(line):
            refuse("Line %d of this %s would introduce %s:\n\n    %s\n\nRemove it, or say why the rung is wrong and drop it back to skill. It was\npromoted because people had to say this repeatedly." % (n, tool, WHAT, line.strip()))
sys.exit(0)
' || prc=$?

case "$prc" in
  0) _rc=0; exit 0 ;;
  2) exit 2 ;;
  *) printf 'graduated-@@TAG@@: the payload reader exited %s, which is neither allow nor block. Blocking, because an undetermined answer is not a pass.\n' "$prc" >&2
     exit 2 ;;
esac
